name = "Clarity (Main Edition)"
author = "Darkblade360350"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e13aaad920d9a7c1b074dc4afa74f9a2db4edec8d395b3a31f409d76bbf1ef06"

[versions]
minecraft = "1.19.2"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
