name = "Clarity"
author = "Darkblade360350"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f086ee4d189393067f9a8c27644b80a532bac984af2a3e91ad9dbabefd1f65ab"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
